In [12]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# define example
data = ['bad', 'bad', 'not good', 'good', 'not good', 'bad', 'bad', 'good', 'good', 'not good']
values = np.array(data)
print(values)

# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

# invert first example
inverted = label_encoder.inverse_transform([np.argmax(onehot_encoded[3, :])])
print(inverted)

['bad' 'bad' 'not good' 'good' 'not good' 'bad' 'bad' 'good' 'good'
 'not good']
[0 0 2 1 2 0 0 1 1 2]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
['good']
